spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/lwala
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: devbytes2020
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true
